old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        product_reindex:
            connection:       default
            exchange_options: { name: 'product_reindex', type: direct }
            queue_options:    { name: 'product_reindex' }

    consumers:
        product_reindex:
            connection:       default
            exchange_options: { name: 'product_reindex', type: direct }
            queue_options:    { name: 'product_reindex'}
            qos_options:      { prefetch_count: 1 }
            callback:         App\Product\Index\ReindexProductConsumer
